spring:
  application:
    name: f1-betting-service
  datasource:
    url: jdbc:h2:mem:f1-betting-service-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true

open-f1:
    base-url: https://api.openf1.org/v1
